import { WeekPlan, DayPlan } from '@/types'

const week1Day1: DayPlan = {
  day: 1,
  breakfast: {
    id: 'w1d1-b',
    name: 'All Bran Bowl with Milk and Avocado',
    type: 'breakfast',
    calories: 310,
    prepTime: 4,
    ingredients: [
      '1/2 cup All Bran cereal',
      '3/4 cup 1% cow milk',
      '1/2 avocado',
      'Squeeze of lemon',
      'Pinch of chili flakes',
      'Black pepper',
    ],
    steps: [
      'Pour 1/2 cup All Bran into a bowl.',
      'Add 3/4 cup cold 1% cow milk. Let sit 2 min so bran softens.',
      'Slice 1/2 avocado on the side, squeeze lemon over it, add chili flakes or black pepper.',
      'Eat the avocado first to slow absorption of the bran carbohydrates.',
    ],
    alternative: 'Swap All Bran for 1/3 cup steel-cut oats plus milk (~290 kcal)',
    tags: ['high-fibre', 'high-protein'],
    hasAvocado: true,
  },
  lunch: {
    id: 'w1d1-l',
    name: 'Chicken and Chickpea Bowl',
    type: 'lunch',
    calories: 340,
    prepTime: 10,
    ingredients: [
      '100g cooked chicken breast',
      '1/2 cup canned chickpeas low-sodium rinsed',
      'Handful of arugula',
      'Cherry tomatoes',
      '1/4 avocado diced',
      '1 tsp olive oil',
      'Squeeze of lemon',
      'Black pepper',
    ],
    steps: [
      'Slice or shred the cooked chicken breast.',
      'Toss with rinsed chickpeas, arugula, and halved cherry tomatoes.',
      'Add diced avocado on top.',
      'Dress with 1 tsp olive oil plus squeeze of lemon plus black pepper.',
    ],
    alternative: 'Swap for pre-cooked rotisserie chicken breast shredded (~320 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w1d1-d',
    name: 'Air Fryer Chicken Thighs and Asparagus',
    type: 'dinner',
    calories: 430,
    prepTime: 25,
    ingredients: [
      '2 bone-in chicken thighs',
      '6 asparagus spears',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      'Black pepper',
      'Olive oil spray',
      '1 lemon wedge',
    ],
    steps: [
      'Preheat air fryer 3 min at 400F.',
      'Pat chicken thighs completely dry for crispy skin.',
      'Rub both sides with garlic powder, smoked paprika, and black pepper.',
      'Air fry skin-side down 12 min, then flip and cook 10 more min.',
      'In the last 8 min, add asparagus spears tossed in olive oil spray alongside.',
      'Rest chicken 2 min before serving. Serve with lemon wedge.',
    ],
    alternative: 'Swap thighs for pork chops same temp 14 min total (~390 kcal)',
    tags: ['high-protein', 'air-fryer'],
    isAirFryer: true,
  },
  leftover: 'Save 1 thigh for Day 2 lunch. Cook an extra chicken breast now for no extra effort.',
}

const week1Day2: DayPlan = {
  day: 2,
  breakfast: {
    id: 'w1d2-b',
    name: 'Green Avocado Smoothie',
    type: 'breakfast',
    calories: 285,
    prepTime: 5,
    ingredients: [
      '1/2 ripe avocado',
      '1 cup 1% cow milk',
      '1 cup fresh baby spinach',
      '1/2 frozen banana',
      '1 tbsp ground flaxseed',
      '4 ice cubes',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 30 to 40 seconds until completely smooth.',
      'Pour into a glass and drink immediately.',
      'The avocado adds creaminess and spinach is tasteless when blended.',
    ],
    alternative: 'Swap banana for 1/2 cup frozen blueberries (~265 kcal lower glycemic)',
    tags: ['smoothie', 'high-fibre', 'high-protein'],
    hasAvocado: true,
    isSmoothie: true,
  },
  lunch: {
    id: 'w1d2-l',
    name: 'Leftover Chicken Lettuce Wraps',
    type: 'lunch',
    calories: 290,
    prepTime: 5,
    ingredients: [
      '1 leftover chicken thigh skin removed',
      '3 to 4 large romaine leaves',
      '1/4 avocado sliced',
      '1 lime halved',
    ],
    steps: [
      'Shred or slice leftover Day 1 chicken thigh and remove skin.',
      'Lay 3 to 4 romaine leaves flat on a plate.',
      'Fill each leaf with chicken and avocado slices.',
      'Squeeze lime juice over everything.',
    ],
    alternative: 'Swap romaine for 1 low-carb tortilla if preferred (~+50 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w1d2-d',
    name: 'Pan-Seared Sirloin Steak and Asparagus',
    type: 'dinner',
    calories: 520,
    prepTime: 15,
    ingredients: [
      '150g sirloin steak',
      '8 asparagus spears',
      '1 tsp garlic powder',
      '1 tsp olive oil',
      '1 clove garlic minced',
      '1 lemon',
      'Black pepper',
    ],
    steps: [
      'Take steak out of fridge 10 min before cooking. Pat completely dry.',
      'Season with black pepper and garlic powder.',
      'Heat cast-iron pan on HIGH until very hot. Add 1 tsp olive oil.',
      'Sear steak 3 to 4 min per side. Do not move it while searing.',
      'Rest 3 min on a cutting board.',
      'While resting cook asparagus with minced garlic 3 to 4 min in same pan.',
      'Slice steak against the grain. Serve with asparagus and lemon.',
    ],
    alternative: 'Swap sirloin for flank steak or chicken breast (~440 kcal)',
    tags: ['high-protein', 'steak'],
  },
  leftover: 'Cook 2 steaks. Cold sliced steak over salad tomorrow is excellent.',
}

const week1Day3: DayPlan = {
  day: 3,
  breakfast: {
    id: 'w1d3-b',
    name: 'All Bran Protein Smoothie',
    type: 'breakfast',
    calories: 270,
    prepTime: 5,
    ingredients: [
      '1/4 cup All Bran cereal',
      '1 cup 1% cow milk',
      '1 scoop unsweetened protein powder',
      '1 tbsp ground flaxseed',
      '4 ice cubes',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 40 seconds. The All Bran blends completely smooth and adds fibre.',
      'Pour and drink immediately.',
    ],
    alternative: 'Swap protein powder for 1/2 cup Greek yogurt blended in (~265 kcal)',
    tags: ['smoothie', 'high-fibre', 'high-protein'],
    isSmoothie: true,
  },
  lunch: {
    id: 'w1d3-l',
    name: 'Steak and Arugula Salad',
    type: 'lunch',
    calories: 320,
    prepTime: 5,
    ingredients: [
      'Leftover Day 2 steak sliced thin',
      'Large handful of arugula',
      'Cherry tomatoes halved',
      '1/4 red onion sliced',
      '1/4 avocado sliced',
      '1 tsp olive oil',
      '1 tsp apple cider vinegar',
      'Black pepper',
    ],
    steps: [
      'Slice leftover Day 2 steak thin against the grain.',
      'Arrange over arugula with cherry tomatoes and red onion.',
      'Fan avocado slices over the top.',
      'Dress with olive oil plus apple cider vinegar plus pepper.',
    ],
    alternative: 'Swap steak for leftover chicken thigh (~290 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w1d3-d',
    name: 'Air Fryer Pork Chops and Roasted Corn',
    type: 'dinner',
    calories: 480,
    prepTime: 20,
    ingredients: [
      '2 boneless pork chops 120g each',
      '1/2 ear of corn',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      '1 tsp dried oregano',
      'Black pepper',
      'Olive oil spray',
      'Pinch of chili powder',
    ],
    steps: [
      'Preheat air fryer 3 min at 400F.',
      'Rub pork chops with garlic powder, smoked paprika, oregano, and pepper.',
      'Air fry pork chops 7 min per side.',
      'Cut corn kernels off 1/2 ear, toss with olive oil spray and chili powder.',
      'Add corn to air fryer for the last 5 min alongside pork.',
      'Rest pork 2 min. Eat pork first then corn.',
    ],
    alternative: 'Swap pork for chicken breast and swap corn for roasted broccoli (~380 kcal)',
    tags: ['high-protein', 'air-fryer', 'moderate-carb'],
    isAirFryer: true,
  },
  leftover: 'Slice extra pork for Day 4 lunch. Double the corn for tomorrow.',
}

const week1Day4: DayPlan = {
  day: 4,
  breakfast: {
    id: 'w1d4-b',
    name: 'All Bran Milk and Egg Bowl',
    type: 'breakfast',
    calories: 310,
    prepTime: 8,
    ingredients: [
      '1/2 cup All Bran cereal',
      '3/4 cup 1% cow milk',
      '1 egg',
      '1/4 avocado',
      '1/2 tsp olive oil',
      'Black pepper',
      'Lemon wedge',
    ],
    steps: [
      'Pour 1/2 cup All Bran into a bowl with 3/4 cup milk. Set aside to soak.',
      'Heat 1/2 tsp olive oil in a small pan over medium heat.',
      'Cook egg scrambled or fried for 3 min.',
      'Serve egg alongside the cereal bowl.',
      'Add 1/4 avocado sliced on the side with pepper and lemon.',
      'Eat avocado and egg before the All Bran.',
    ],
    alternative: 'Swap All Bran for 1/3 cup oats cooked in milk (~300 kcal)',
    tags: ['high-fibre', 'high-protein'],
    hasAvocado: true,
  },
  lunch: {
    id: 'w1d4-l',
    name: 'Pork and Corn Greens Bowl',
    type: 'lunch',
    calories: 350,
    prepTime: 5,
    ingredients: [
      '100g leftover Day 3 pork chop sliced',
      'Leftover corn kernels from 1/4 ear',
      'Large handful mixed greens or spinach',
      '1 tbsp pumpkin seeds',
      '1 tsp olive oil',
      'Juice of 1/2 lemon',
    ],
    steps: [
      'Slice 100g leftover pork chop.',
      'Toss mixed greens with lemon juice.',
      'Add pork, corn kernels, and pumpkin seeds.',
      'Drizzle 1 tsp olive oil over everything.',
      'Eat pork and greens first before the corn.',
    ],
    alternative: 'Swap mixed greens for arugula (~340 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  dinner: {
    id: 'w1d4-d',
    name: 'Ground Beef and Black Bean Skillet',
    type: 'dinner',
    calories: 430,
    prepTime: 15,
    ingredients: [
      '150g lean ground beef 90 percent lean',
      '1/2 cup black beans canned low-sodium rinsed',
      '1/2 yellow onion diced',
      '1 clove garlic minced',
      '1/2 tsp cumin',
      '1/2 tsp smoked paprika',
      'Chili flakes to taste',
      '1 tsp olive oil',
      '1 bag cauliflower rice microwaveable',
    ],
    steps: [
      'Heat 1 tsp olive oil in a large pan on medium-high.',
      'Add ground beef. Break apart and cook 5 to 6 min until browned.',
      'Drain any excess fat.',
      'Add diced onion and minced garlic. Cook 2 min.',
      'Add black beans, cumin, smoked paprika, and chili flakes. Stir 2 more min.',
      'Microwave cauliflower rice 4 min and serve the skillet over it.',
    ],
    alternative: 'Swap cauliflower rice for 1/2 cup cooled white rice (+90 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  leftover: 'Double the beef skillet. Serves Day 5 lunch. Keeps 3 days in fridge.',
}

const week1Day5: DayPlan = {
  day: 5,
  breakfast: {
    id: 'w1d5-b',
    name: 'Banana Avocado Milk Smoothie',
    type: 'breakfast',
    calories: 280,
    prepTime: 5,
    ingredients: [
      '1/2 frozen banana',
      '1/4 ripe avocado',
      '1 cup 1% cow milk',
      '1 scoop unsweetened protein powder',
      '1 tbsp ground flaxseed',
      '4 ice cubes',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 30 to 40 seconds until smooth and creamy.',
      'The avocado gives it a thick milkshake texture.',
      'Drink immediately. Do not add honey or sugar.',
    ],
    alternative: 'Swap banana for 1/2 cup frozen blueberries (~255 kcal)',
    tags: ['smoothie', 'high-protein', 'moderate-carb'],
    hasAvocado: true,
    isSmoothie: true,
  },
  lunch: {
    id: 'w1d5-l',
    name: 'Leftover Beef and Black Bean Wraps',
    type: 'lunch',
    calories: 370,
    prepTime: 5,
    ingredients: [
      'Leftover Day 4 beef skillet',
      '3 to 4 large romaine leaves',
      'Juice of 1/2 lime',
      '1/4 avocado sliced',
    ],
    steps: [
      'Reheat leftover Day 4 skillet 2 min in a pan.',
      'Spoon filling into 3 to 4 romaine leaves.',
      'Top with lime juice and avocado slices.',
    ],
    alternative: 'Serve over arugula as a salad bowl (~360 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w1d5-d',
    name: 'Air Fryer Chicken Wings and Baked Potato',
    type: 'dinner',
    calories: 500,
    prepTime: 28,
    ingredients: [
      '5 chicken wings',
      '1 small potato 120g',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      'Black pepper',
      '2 tbsp plain Greek yogurt',
      'Chives or dried chives',
    ],
    steps: [
      'Pierce potato all over with a fork. Microwave 8 to 10 min until soft.',
      'Set potato aside to cool 10 to 15 min to build resistant starch.',
      'Preheat air fryer to 400F.',
      'Pat wings completely dry. Season with garlic powder, paprika, and pepper.',
      'Air fry 12 min, flip, then 10 more min until very crispy.',
      'Top cooled potato with Greek yogurt plus chives plus pepper. No butter.',
      'Eat wings first then potato.',
    ],
    alternative: 'Swap potato for roasted broccoli to save ~90 kcal (~410 kcal)',
    tags: ['high-protein', 'air-fryer', 'moderate-carb'],
    isAirFryer: true,
  },
  leftover: 'Extra wings for Day 6. Refrigerate potato overnight.',
}

const week2Day6: DayPlan = {
  day: 6,
  breakfast: {
    id: 'w2d6-b',
    name: 'Veggie Egg Muffins and All Bran Milk',
    type: 'breakfast',
    calories: 295,
    prepTime: 22,
    ingredients: [
      '6 eggs',
      '1/2 bell pepper diced',
      'Handful mushrooms diced',
      'Handful spinach',
      'Black pepper',
      'Dried herbs',
      'Olive oil spray',
      '1/4 cup All Bran cereal',
      '1/2 cup 1% cow milk',
    ],
    steps: [
      'Preheat oven to 350F. Spray a 6-cup muffin tin with olive oil.',
      'Dice bell pepper and mushrooms. Divide evenly among the 6 cups.',
      'Whisk 6 eggs with black pepper and dried herbs. Pour over veggies.',
      'Bake 18 min until set and golden. Cool 2 min in tin.',
      'Eat 3 muffins now (~210 kcal). Refrigerate the rest for Day 7.',
      'Alongside: 1/4 cup All Bran plus 1/2 cup milk (~85 kcal). Eat muffins first.',
    ],
    alternative: 'Add diced cooked ground beef to muffin cups for more protein (~+40 kcal)',
    tags: ['high-protein'],
  },
  lunch: {
    id: 'w2d6-l',
    name: 'Cold Wing and Arugula Bowl',
    type: 'lunch',
    calories: 280,
    prepTime: 5,
    ingredients: [
      'Leftover Day 5 chicken wings',
      'Large handful arugula',
      'Cherry tomatoes halved',
      '1/4 red onion sliced',
      '1 tsp olive oil',
      '1 tsp apple cider vinegar',
      'Black pepper',
    ],
    steps: [
      'Shred meat from leftover Day 5 wings.',
      'Toss over arugula with cherry tomatoes and red onion.',
      'Dress with 1 tsp olive oil plus apple cider vinegar plus black pepper.',
    ],
    alternative: 'Swap for rotisserie chicken low-sodium shredded (~290 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  dinner: {
    id: 'w2d6-d',
    name: 'Beef Strips and Asparagus Stir Fry',
    type: 'dinner',
    calories: 470,
    prepTime: 12,
    ingredients: [
      '150g lean beef sirloin or flank sliced thin',
      '8 asparagus spears cut into 2 inch pieces',
      '1 tsp sesame oil',
      '1 clove garlic minced',
      '1 tsp fresh ginger grated',
      '1 tbsp low-sodium soy sauce',
      '1/2 bag cauliflower rice microwaveable',
      'Black pepper',
    ],
    steps: [
      'Slice 150g lean beef into thin strips. Season with black pepper.',
      'Heat 1 tsp sesame oil in wok or large pan on high.',
      'Add beef and cook 2 to 3 min stirring constantly. Remove and set aside.',
      'Add minced garlic and grated ginger. Stir 30 sec.',
      'Add asparagus and soy sauce. Stir fry 3 min.',
      'Return beef, toss together 1 min. Serve over cauliflower rice.',
    ],
    alternative: 'Swap beef for chicken breast strips and swap asparagus for broccoli (~440 kcal)',
    tags: ['high-protein', 'high-fibre', 'steak'],
  },
  leftover: '3 egg muffins in fridge for Day 7 breakfast. Stir fry reheats well for Day 7 lunch.',
}

const week2Day7: DayPlan = {
  day: 7,
  breakfast: {
    id: 'w2d7-b',
    name: 'Leftover Egg Muffins and Avocado',
    type: 'breakfast',
    calories: 210,
    prepTime: 2,
    ingredients: [
      '3 leftover egg muffins from Day 6',
      '1/4 avocado sliced',
      'Lemon wedge',
      'Black coffee or 1% milk',
    ],
    steps: [
      'Reheat 3 egg muffins from Day 6 for 1 min in microwave.',
      'Serve with 1/4 avocado sliced on the side plus lemon.',
      'Black coffee or a glass of 1% milk alongside.',
    ],
    alternative: 'Swap for All Bran plus milk plus avocado bowl (~310 kcal)',
    tags: ['high-protein'],
    hasAvocado: true,
  },
  lunch: {
    id: 'w2d7-l',
    name: 'Leftover Beef and Asparagus Bowl',
    type: 'lunch',
    calories: 340,
    prepTime: 3,
    ingredients: [
      'Leftover Day 6 beef stir fry',
      'Handful fresh spinach',
      'Sesame seeds',
      '1 lemon wedge',
      '1/4 avocado diced',
    ],
    steps: [
      'Reheat Day 6 stir fry in pan 2 min on medium.',
      'Add a handful of fresh spinach while warming. It wilts instantly.',
      'Top with sesame seeds and lemon squeeze.',
      'Add diced avocado on the side.',
    ],
    alternative: 'Serve cold over mixed greens instead of reheating (~320 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w2d7-d',
    name: 'Air Fryer Chicken Thighs and Cauliflower Mash',
    type: 'dinner',
    calories: 520,
    prepTime: 25,
    ingredients: [
      '2 bone-in chicken thighs',
      '2 cups cauliflower florets',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      '1 tsp dried oregano',
      'Black pepper',
      '1 tsp olive oil',
      '1 clove garlic minced',
      '2 tbsp 1% cow milk warm',
    ],
    steps: [
      'Preheat air fryer 3 min at 400F. Season thighs with garlic powder, paprika, oregano, pepper.',
      'Air fry skin-side down 12 min, flip, 10 more min.',
      'While chicken cooks microwave cauliflower florets in splash of water covered for 6 min.',
      'Drain. Mash with 1 tsp olive oil plus minced garlic plus 2 tbsp warm milk plus pepper.',
      'Serve 1 thigh over cauliflower mash.',
    ],
    alternative: 'Swap thighs for drumsticks. Swap mash for roasted broccoli (~460 kcal)',
    tags: ['high-protein', 'air-fryer', 'high-fibre'],
    isAirFryer: true,
  },
  leftover: 'Save 1 thigh for Day 8 lunch. Extra cauliflower mash keeps 2 days.',
}

const week2Day8: DayPlan = {
  day: 8,
  breakfast: {
    id: 'w2d8-b',
    name: 'Strawberry All Bran Smoothie',
    type: 'breakfast',
    calories: 270,
    prepTime: 5,
    ingredients: [
      '1/4 cup All Bran cereal',
      '1 cup 1% cow milk',
      '1/2 cup frozen strawberries',
      '1 scoop unsweetened protein powder',
      '1 tbsp chia seeds',
      '4 ice cubes',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 40 seconds. The All Bran blends smooth and adds fibre.',
      'Pour and drink immediately.',
      'Optional: add 1 tsp natural peanut butter for extra fat (+50 kcal).',
    ],
    alternative: 'Swap strawberries for blueberries or raspberries (same kcal)',
    tags: ['smoothie', 'high-fibre', 'high-protein'],
    isSmoothie: true,
  },
  lunch: {
    id: 'w2d8-l',
    name: 'Chicken and Corn Salad',
    type: 'lunch',
    calories: 330,
    prepTime: 7,
    ingredients: [
      'Leftover Day 7 chicken thigh skin removed',
      '1/4 ear corn kernels or frozen microwaved 2 min',
      'Large handful mixed greens',
      '1/4 avocado sliced',
      'Juice of 1 lime',
      '1 tsp olive oil',
      'Chili flakes',
    ],
    steps: [
      'Shred leftover Day 7 chicken thigh and remove skin.',
      'Cut kernels off 1/4 ear corn or microwave frozen corn 2 min.',
      'Toss chicken plus corn plus mixed greens plus avocado together.',
      'Dress with lime juice plus 1 tsp olive oil plus chili flakes.',
      'Eat chicken and greens first then corn.',
    ],
    alternative: 'Swap corn for roasted cherry tomatoes (~280 kcal lower carb)',
    tags: ['high-protein', 'high-fibre', 'moderate-carb'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w2d8-d',
    name: 'Ground Beef Stuffed Bell Peppers',
    type: 'dinner',
    calories: 510,
    prepTime: 30,
    ingredients: [
      '2 large bell peppers halved lengthwise seeds removed',
      '180g lean ground beef 90 percent lean',
      '1 clove garlic minced',
      '1/2 tsp cumin',
      '1/2 cup black beans canned low-sodium rinsed',
      '2 tbsp no-salt diced tomatoes',
      'Pinch of low-sodium shredded cheese',
    ],
    steps: [
      'Preheat oven to 375F. Halve 2 large bell peppers and remove seeds. Place on baking tray.',
      'Cook 180g lean ground beef on medium-high 5 to 6 min breaking up. Drain fat.',
      'Add minced garlic plus 1/2 tsp cumin plus black beans plus diced tomatoes. Stir 2 min.',
      'Spoon filling into 4 pepper halves. Top each with a pinch of shredded cheese.',
      'Bake 18 to 20 min until peppers are tender.',
    ],
    alternative: 'Swap ground beef for ground chicken. Add 1/4 cup corn to filling (~490 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  leftover: 'Make 4 pepper halves. The extra 2 are Day 9 lunch. Better cold or reheated.',
}

const week2Day9: DayPlan = {
  day: 9,
  breakfast: {
    id: 'w2d9-b',
    name: 'Greek Yogurt Parfait with All Bran',
    type: 'breakfast',
    calories: 240,
    prepTime: 4,
    ingredients: [
      '3/4 cup plain 0% Greek yogurt',
      '3 tbsp All Bran cereal',
      'Handful blueberries',
      '1 tbsp ground flaxseed',
      'Dash of cinnamon',
    ],
    steps: [
      'Layer in a bowl: Greek yogurt then All Bran then blueberries then flaxseed then cinnamon.',
      'No honey and no granola.',
      'The All Bran replaces granola with more fibre and less sugar.',
    ],
    alternative: 'Swap All Bran for chia seeds (~200 kcal). Swap yogurt for cottage cheese.',
    tags: ['high-protein', 'high-fibre'],
  },
  lunch: {
    id: 'w2d9-l',
    name: 'Leftover Stuffed Peppers',
    type: 'lunch',
    calories: 290,
    prepTime: 3,
    ingredients: [
      '2 leftover stuffed pepper halves from Day 8',
      'Handful arugula',
      '1 tsp olive oil',
      '1 lemon wedge',
    ],
    steps: [
      'Reheat 2 leftover pepper halves 2 min in microwave or eat cold.',
      'Side: arugula plus 1 tsp olive oil plus lemon.',
    ],
    alternative: 'Scoop filling into a lettuce bowl if peppers are too soft (~270 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  dinner: {
    id: 'w2d9-d',
    name: 'Air Fryer Pork Chops and Baked Potato',
    type: 'dinner',
    calories: 490,
    prepTime: 25,
    ingredients: [
      '2 boneless pork chops 110g each',
      '1 small potato 120g',
      '1 tsp garlic powder',
      '1 tsp dried oregano',
      'Black pepper',
      '2 tbsp plain Greek yogurt',
      'Chives',
    ],
    steps: [
      'Pierce 1 small potato with a fork. Microwave 8 to 10 min. Set aside to cool 10 min.',
      'Preheat air fryer 3 min at 400F. Rub pork chops with garlic powder plus oregano plus pepper.',
      'Air fry 7 min per side until cooked through.',
      'Top cooled potato with Greek yogurt plus chives plus pepper. No butter.',
      'Eat pork chop first then the potato.',
    ],
    alternative: 'Swap potato for roasted cauliflower to save ~90 kcal (~400 kcal)',
    tags: ['high-protein', 'air-fryer', 'moderate-carb'],
    isAirFryer: true,
  },
  leftover: 'Slice extra pork for Day 10 bowl. Refrigerate potato overnight.',
}

const week2Day10: DayPlan = {
  day: 10,
  breakfast: {
    id: 'w2d10-b',
    name: 'Savory Oatmeal and Soft Egg',
    type: 'breakfast',
    calories: 265,
    prepTime: 10,
    ingredients: [
      '1/3 cup steel-cut oats',
      '1/2 cup water',
      '1/2 cup 1% cow milk',
      '2 tbsp All Bran cereal',
      '1 egg',
      'Handful spinach sauteed',
      'Black pepper',
    ],
    steps: [
      'Cook 1/3 cup steel-cut oats in 1/2 cup water plus 1/2 cup milk for 7 to 8 min.',
      'Stir in 2 tbsp All Bran after cooking for extra fibre.',
      'Soft-boil 1 egg: simmer in water 6 min. Peel.',
      'Top oats with sauteed spinach plus sliced egg plus black pepper. No sugar.',
    ],
    alternative: 'Swap for 1/2 cup All Bran plus 3/4 cup milk (~240 kcal)',
    tags: ['high-fibre', 'high-protein'],
  },
  lunch: {
    id: 'w2d10-l',
    name: 'Pork and Potato Bowl',
    type: 'lunch',
    calories: 350,
    prepTime: 5,
    ingredients: [
      '100g leftover Day 9 pork chop sliced',
      'Leftover cold potato cubed',
      'Large handful arugula',
      '1 tbsp pumpkin seeds',
      '1 tsp olive oil',
      '1 tsp apple cider vinegar',
    ],
    steps: [
      'Slice 100g leftover pork chop.',
      'Cube the cold leftover potato. Resistant starch is higher now.',
      'Toss pork and potato over arugula with pumpkin seeds.',
      'Dress with 1 tsp olive oil plus apple cider vinegar.',
      'Eat pork first.',
    ],
    alternative: 'Swap potato for roasted cauliflower (~270 kcal)',
    tags: ['high-protein', 'high-fibre', 'moderate-carb'],
  },
  dinner: {
    id: 'w2d10-d',
    name: 'Pan-Seared Flank Steak and Asparagus',
    type: 'dinner',
    calories: 510,
    prepTime: 15,
    ingredients: [
      '150g flank steak',
      '8 asparagus spears',
      '1 tsp olive oil',
      '1 clove garlic minced',
      '1 lemon',
      'Black pepper',
      'Garlic powder',
    ],
    steps: [
      'Score 150g flank steak lightly across the grain. Season with pepper plus garlic powder.',
      'Heat heavy pan on high. Add 1 tsp olive oil.',
      'Sear 3 to 4 min each side. Do not move while searing.',
      'Rest 3 min on a board.',
      'Same pan medium heat: cook asparagus with minced garlic plus lemon 3 to 4 min.',
      'Slice steak thin against the grain. Serve with asparagus.',
    ],
    alternative: 'Swap flank for sirloin or ribeye. Swap asparagus for zucchini (~490 kcal)',
    tags: ['high-protein', 'steak'],
  },
  leftover: 'Cook 2 steaks. Cold sliced steak is great over Day 11 salad.',
}

const week3Day11: DayPlan = {
  day: 11,
  breakfast: {
    id: 'w3d11-b',
    name: 'Tofu Scramble and All Bran Milk',
    type: 'breakfast',
    calories: 225,
    prepTime: 10,
    ingredients: [
      '1/2 block firm tofu pressed',
      '1/2 onion diced',
      '1/2 bell pepper diced',
      '1/2 tsp turmeric',
      '1 tbsp nutritional yeast',
      '1 tsp olive oil',
      'Black pepper',
      '1/4 cup All Bran cereal',
      '1/2 cup 1% cow milk',
    ],
    steps: [
      'Press 1/2 block firm tofu in a paper towel. Crumble into chunks.',
      'Heat 1 tsp olive oil in pan on medium-high. Add diced onion and bell pepper. Cook 2 min.',
      'Add tofu plus 1/2 tsp turmeric plus 1 tbsp nutritional yeast plus pepper. Stir 4 to 5 min until golden.',
      'Alongside: 1/4 cup All Bran plus 1/2 cup 1% milk. Eat scramble first then cereal.',
    ],
    alternative: 'Swap tofu for 3 eggs same method classic scramble (~270 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  lunch: {
    id: 'w3d11-l',
    name: 'Steak and Avocado Greens Bowl',
    type: 'lunch',
    calories: 320,
    prepTime: 5,
    ingredients: [
      'Leftover Day 10 steak sliced thin',
      'Large handful mixed greens',
      'Cherry tomatoes halved',
      '1 tbsp sliced almonds',
      '1 tsp olive oil',
      '1 tsp apple cider vinegar',
      '1/4 avocado sliced',
    ],
    steps: [
      'Slice leftover Day 10 steak thin against the grain.',
      'Toss mixed greens with steak plus cherry tomatoes plus almonds.',
      'Dress with 1 tsp olive oil plus apple cider vinegar.',
      'Fan 1/4 avocado sliced on top.',
    ],
    alternative: 'Swap mixed greens for arugula. Swap steak for cooked chicken breast (~290 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w3d11-d',
    name: 'Air Fryer Chicken Drumsticks and Mashed Potato',
    type: 'dinner',
    calories: 500,
    prepTime: 28,
    ingredients: [
      '3 chicken drumsticks',
      '1 small potato 120g',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      '1 tsp dried oregano',
      'Black pepper',
      '1 tsp olive oil',
      '2 tbsp 1% cow milk warm',
      '1 clove garlic minced',
    ],
    steps: [
      'Preheat air fryer 3 min at 400F. Pat 3 drumsticks dry.',
      'Rub with garlic powder plus smoked paprika plus oregano plus pepper.',
      'Air fry 13 min, flip, 12 more min until skin is crispy.',
      'Meanwhile microwave 1 small potato 8 min. Mash with 1 tsp olive oil plus 2 tbsp warm milk plus garlic plus pepper. Keep skin on for fibre.',
      'Eat at least 1 drumstick before touching the potato.',
    ],
    alternative: 'Swap mashed potato for cauliflower mash (~430 kcal). Swap drumsticks for thighs.',
    tags: ['high-protein', 'air-fryer', 'moderate-carb'],
    isAirFryer: true,
  },
  leftover: 'Extra drumsticks for Day 12 lunch. Refrigerate mashed potato and reheat with splash of milk.',
}

const week3Day12: DayPlan = {
  day: 12,
  breakfast: {
    id: 'w3d12-b',
    name: 'Chocolate Avocado Milk Smoothie',
    type: 'breakfast',
    calories: 285,
    prepTime: 5,
    ingredients: [
      '1/2 ripe avocado',
      '1 cup 1% cow milk',
      '1 scoop unsweetened chocolate or vanilla protein powder',
      '1 tbsp ground flaxseed',
      '1 tsp unsweetened cocoa powder',
      '4 ice cubes',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 30 to 40 seconds until smooth and velvety.',
      'The avocado makes this taste like a chocolate milkshake with zero sugar added.',
      'Drink immediately. Perfect post-workout or fast morning breakfast.',
    ],
    alternative: 'Swap cocoa for cinnamon plus 1/4 banana for a warmer flavour (~280 kcal)',
    tags: ['smoothie', 'high-protein', 'high-fibre'],
    hasAvocado: true,
    isSmoothie: true,
  },
  lunch: {
    id: 'w3d12-l',
    name: 'Drumstick and Corn Avocado Bowl',
    type: 'lunch',
    calories: 340,
    prepTime: 7,
    ingredients: [
      'Leftover Day 11 drumsticks meat pulled off bone',
      '1/4 ear corn kernels microwaved 4 min',
      'Large handful mixed greens',
      'Cherry tomatoes halved',
      '1/4 avocado sliced',
      '1 tsp olive oil',
      'Juice of 1 lime',
      'Black pepper',
    ],
    steps: [
      'Pull meat off leftover Day 11 drumsticks.',
      'Microwave 1/4 ear corn kernels 4 min.',
      'Toss chicken plus corn plus mixed greens plus cherry tomatoes.',
      'Add 1/4 avocado sliced on top.',
      'Dress with lime dressing: 1 tsp olive oil plus lime plus pepper.',
      'Eat chicken first then corn.',
    ],
    alternative: 'Swap corn for roasted asparagus spears (~280 kcal)',
    tags: ['high-protein', 'high-fibre', 'moderate-carb'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w3d12-d',
    name: 'Ground Beef and Chickpea Skillet',
    type: 'dinner',
    calories: 430,
    prepTime: 15,
    ingredients: [
      '150g lean ground beef 90 percent lean',
      '1/2 cup chickpeas canned low-sodium rinsed',
      '1 clove garlic minced',
      '1/2 tsp cumin',
      '1/2 tsp smoked paprika',
      '2 tbsp no-salt diced tomatoes',
      '1 tsp olive oil',
      '1 lemon wedge',
      '1/4 avocado on the side',
      'Large side salad',
    ],
    steps: [
      'Heat 1 tsp olive oil in pan on medium-high.',
      'Cook 150g lean ground beef 5 min, breaking apart. Drain excess fat.',
      'Add 1 minced garlic plus 1/2 tsp cumin plus 1/2 tsp smoked paprika. Stir 1 min.',
      'Add chickpeas plus 2 tbsp no-salt diced tomatoes. Cook 3 min.',
      'Finish with lemon. Serve with a large side salad and 1/4 avocado on the side.',
    ],
    alternative: 'Swap beef for ground chicken. Swap chickpeas for black beans (~420 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  leftover: 'Double the beef skillet. Covers Day 13 lunch. Freeze one portion.',
}

const week3Day13: DayPlan = {
  day: 13,
  breakfast: {
    id: 'w3d13-b',
    name: 'Cottage Cheese All Bran and Berries',
    type: 'breakfast',
    calories: 190,
    prepTime: 3,
    ingredients: [
      '3/4 cup low-fat cottage cheese',
      '3 tbsp All Bran cereal',
      '1/2 cup blueberries or raspberries',
      '1 tbsp ground flaxseed',
      'Dash of cinnamon',
      'Splash of 1% milk',
    ],
    steps: [
      'Layer in a bowl: cottage cheese then All Bran then berries then flaxseed then cinnamon.',
      'Add a splash of 1% milk over top to moisten the bran.',
      'No cooking required.',
    ],
    alternative: 'Swap for Greek yogurt parfait plus All Bran (~240 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  lunch: {
    id: 'w3d13-l',
    name: 'Leftover Beef and Chickpea Wraps',
    type: 'lunch',
    calories: 360,
    prepTime: 5,
    ingredients: [
      'Leftover Day 12 beef and chickpea skillet',
      '3 to 4 large romaine leaves',
      'Juice of 1 lime',
      '1/4 avocado sliced',
    ],
    steps: [
      'Reheat Day 12 skillet 2 min.',
      'Spoon into romaine leaves or over arugula.',
      'Add lime squeeze and avocado slices.',
    ],
    alternative: 'Serve with 1/2 cup cauliflower rice for more volume (~+25 kcal)',
    tags: ['high-protein', 'high-fibre'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w3d13-d',
    name: 'Air Fryer Garlic Chicken Breast and Baked Potato',
    type: 'dinner',
    calories: 500,
    prepTime: 25,
    ingredients: [
      '1 chicken breast',
      '1 small potato 120g',
      '1 tsp garlic powder',
      '1 tsp dried oregano',
      'Black pepper',
      '2 tbsp plain Greek yogurt',
      'Chives',
    ],
    steps: [
      'Pierce 1 small potato with a fork. Microwave 8 to 10 min. Set aside 10 min to cool.',
      'Preheat air fryer 3 min at 380F. Pound chicken breast thin if thick.',
      'Rub with garlic powder plus oregano plus pepper.',
      'Air fry 9 min per side.',
      'Top cooled potato with 2 tbsp plain Greek yogurt plus chives plus pepper. No butter.',
      'Eat chicken first.',
    ],
    alternative: 'Swap potato for roasted broccoli plus cauliflower (~400 kcal)',
    tags: ['high-protein', 'air-fryer', 'moderate-carb'],
    isAirFryer: true,
  },
  leftover: 'Cook extra chicken for Day 14. Refrigerate potato overnight for more resistant starch.',
}

const week3Day14: DayPlan = {
  day: 14,
  breakfast: {
    id: 'w3d14-b',
    name: 'Banana All Bran Milk Smoothie',
    type: 'breakfast',
    calories: 290,
    prepTime: 5,
    ingredients: [
      '1/2 frozen banana',
      '1/4 cup All Bran cereal',
      '1 cup 1% cow milk',
      '1 scoop unsweetened protein powder',
      '1 tbsp almond butter',
      '4 ice cubes',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 40 seconds. The All Bran adds fibre and the almond butter slows the banana sugar release.',
      'Pour and drink immediately.',
      'This is one of the most filling smoothies in the plan.',
    ],
    alternative: 'Swap banana for 1/2 cup blueberries plus 1 tsp vanilla extract (~255 kcal lower glycemic)',
    tags: ['smoothie', 'high-fibre', 'high-protein', 'moderate-carb'],
    isSmoothie: true,
  },
  lunch: {
    id: 'w3d14-l',
    name: 'Chicken and Cold Potato Bowl',
    type: 'lunch',
    calories: 340,
    prepTime: 5,
    ingredients: [
      'Leftover Day 13 chicken breast sliced',
      'Leftover cold potato cubed',
      'Large handful arugula',
      '1 tbsp pumpkin seeds',
      '1 tsp olive oil',
      '1 tsp apple cider vinegar',
      '1/4 avocado',
    ],
    steps: [
      'Slice leftover Day 13 chicken breast.',
      'Cube the cold refrigerated potato. Resistant starch is at its best now.',
      'Toss both over arugula with pumpkin seeds.',
      'Dress with 1 tsp olive oil plus apple cider vinegar.',
      'Add 1/4 avocado on the side. Eat chicken first.',
    ],
    alternative: 'Swap potato for roasted cauliflower (~270 kcal). Swap chicken for leftover ground beef.',
    tags: ['high-protein', 'high-fibre', 'moderate-carb'],
    hasAvocado: true,
  },
  dinner: {
    id: 'w3d14-d',
    name: 'Lentil and Beef Skillet',
    type: 'dinner',
    calories: 460,
    prepTime: 20,
    ingredients: [
      '1/2 cup red lentils dry or 1 can lentils rinsed',
      '100g lean ground beef',
      '1 clove garlic minced',
      '1/2 tsp smoked paprika',
      '1 lemon',
      'Black pepper',
      'Handful spinach sauteed on the side',
    ],
    steps: [
      'If using dry lentils: rinse 1/2 cup red lentils, cook in 1 cup water 12 min until soft.',
      'If using canned lentils: rinse and skip step 1.',
      'In a separate pan: cook 100g lean ground beef 5 min on medium-high. Drain fat.',
      'Add 1 minced garlic plus 1/2 tsp smoked paprika plus cooked lentils. Stir 2 min.',
      'Finish with lemon juice plus pepper. Serve with sauteed spinach on the side.',
    ],
    alternative: 'Swap beef for ground chicken. Use canned lentils to cut time to 10 min (~440 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  leftover: 'Double the lentil-beef skillet. Day 15 lunch covered. Freeze one portion as emergency meal.',
}

const week3Day15: DayPlan = {
  day: 15,
  breakfast: {
    id: 'w3d15-b',
    name: 'Victory Green Smoothie',
    type: 'breakfast',
    calories: 250,
    prepTime: 5,
    ingredients: [
      '1/4 cup All Bran cereal',
      '1 cup 1% cow milk',
      '1 cup frozen spinach',
      '1/4 avocado',
      '1 scoop unsweetened protein powder',
      '1 tbsp ground flaxseed',
      '4 ice cubes',
      'Optional squeeze of lemon',
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend 40 seconds until completely smooth. It turns green and that is the goal.',
      'Pour into a glass. Drink slowly and enjoy. You have made it 15 days.',
      'Optional: squeeze of lemon into the blender for brightness.',
    ],
    alternative: 'Swap for All Bran plus milk plus avocado egg bowl (~310 kcal)',
    tags: ['smoothie', 'high-fibre', 'high-protein'],
    hasAvocado: true,
    isSmoothie: true,
  },
  lunch: {
    id: 'w3d15-l',
    name: 'Leftover Lentil and Beef Bowl',
    type: 'lunch',
    calories: 325,
    prepTime: 3,
    ingredients: [
      'Leftover Day 14 lentil and beef skillet',
      'Juice of 1 lime',
      'Fresh herbs optional',
      'Raw carrot sticks on the side',
    ],
    steps: [
      'Reheat Day 14 skillet 2 min.',
      'Add lime and fresh herbs.',
      'Serve with raw carrot sticks on the side.',
    ],
    alternative: 'Serve in romaine cups instead of as a bowl (~315 kcal)',
    tags: ['high-protein', 'high-fibre'],
  },
  dinner: {
    id: 'w3d15-d',
    name: 'Air Fryer Chicken Thighs with Corn and Asparagus',
    type: 'dinner',
    calories: 500,
    prepTime: 25,
    ingredients: [
      '2 bone-in chicken thighs',
      '6 asparagus spears',
      '1/4 ear corn kernels',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      '1 tsp dried oregano',
      'Black pepper',
      'Olive oil spray',
    ],
    steps: [
      'Preheat air fryer 3 min at 400F. Season 2 thighs with garlic powder plus smoked paprika plus oregano plus pepper.',
      'Air fry skin-side down 12 min, flip 10 more min.',
      'Last 8 min: toss 6 asparagus spears plus 1/4 ear corn kernels in olive oil spray. Add to basket alongside chicken.',
      'Rest chicken 2 min. Eat protein and asparagus first then corn.',
      '15 days done. You built something real and the freezer has your back next week.',
    ],
    alternative: 'Swap corn for roasted cherry tomatoes (~460 kcal). Swap thighs for pork chops.',
    tags: ['high-protein', 'air-fryer', 'moderate-carb'],
    isAirFryer: true,
  },
  leftover: 'You have built habits and a freezer stash. Restart from Day 1 knowing your favourites.',
}

export const WEEK_1: WeekPlan = {
  week: 1,
  days: [week1Day1, week1Day2, week1Day3, week1Day4, week1Day5],
  snacks: [
    { id: 'w1-s1', name: 'Hard-boiled Egg and Veggies', calories: 160, note: '2 eggs plus carrot or cucumber sticks. Batch-boil 6 on Sunday.', alternative: 'Devilled eggs with yogurt and paprika (~150 kcal)' },
    { id: 'w1-s2', name: 'Greek Yogurt and Walnuts', calories: 185, note: '1/2 cup plain 0% yogurt, 5 walnut halves, cinnamon.', alternative: 'Cottage cheese plus almonds (~160 kcal)' },
    { id: 'w1-s3', name: 'Celery and Almond Butter', calories: 105, note: '4 sticks, 1 tbsp almond butter no sugar added.', alternative: 'Cucumber plus natural peanut butter (~110 kcal)' },
    { id: 'w1-s4', name: 'Banana and Peanut Butter', calories: 145, note: '1/2 banana max, 1 tbsp natural PB. Eat PB first.', alternative: '1/2 banana plus 2 tbsp Greek yogurt (~80 kcal)' },
    { id: 'w1-s5', name: 'String Cheese and Almonds', calories: 160, note: '1 low-sodium string cheese plus 10 raw almonds.', alternative: 'Babybel plus 5 walnut halves (~150 kcal)' },
    { id: 'w1-s6', name: 'Air Fryer Chickpeas', calories: 135, note: '1/2 cup rinsed chickpeas, olive oil spray, cumin. 400F 15 min.', alternative: 'Roasted pumpkin seeds (~120 kcal)' },
  ],
  groceryList: [
    { id: 'w1-g1', name: 'Chicken thighs bone-in', quantity: '4 to 6 pcs', category: 'meat' },
    { id: 'w1-g2', name: 'Chicken breast', quantity: '2 pcs', category: 'meat' },
    { id: 'w1-g3', name: 'Chicken wings', quantity: '500g', category: 'meat' },
    { id: 'w1-g4', name: 'Sirloin steak', quantity: '2 x 150g', category: 'meat' },
    { id: 'w1-g5', name: 'Lean ground beef 90 percent', quantity: '300g', category: 'meat' },
    { id: 'w1-g6', name: 'Pork chops boneless', quantity: '4', category: 'meat' },
    { id: 'w1-g7', name: 'Spinach baby bag', quantity: '1 large', category: 'vegetables' },
    { id: 'w1-g8', name: 'Asparagus', quantity: '1 bunch', category: 'vegetables' },
    { id: 'w1-g9', name: 'Mixed greens or arugula', quantity: '2 bags', category: 'vegetables' },
    { id: 'w1-g10', name: 'Cherry tomatoes', quantity: '1 pint', category: 'vegetables' },
    { id: 'w1-g11', name: 'Cucumber', quantity: '2', category: 'vegetables' },
    { id: 'w1-g12', name: 'Bell peppers mixed', quantity: '4', category: 'vegetables' },
    { id: 'w1-g13', name: 'Corn fresh or frozen', quantity: '2 ears or small bag', category: 'vegetables' },
    { id: 'w1-g14', name: 'Cauliflower rice microwaveable', quantity: '2 bags', category: 'vegetables' },
    { id: 'w1-g15', name: 'Small Yukon Gold potatoes', quantity: '3 to 4', category: 'vegetables' },
    { id: 'w1-g16', name: 'Avocados', quantity: '4 to 5', category: 'fats' },
    { id: 'w1-g17', name: 'Almond butter no sugar', quantity: '1 jar', category: 'fats' },
    { id: 'w1-g18', name: 'Ground flaxseed', quantity: '1 bag', category: 'fats' },
    { id: 'w1-g19', name: 'Pumpkin seeds', quantity: 'small bag', category: 'fats' },
    { id: 'w1-g20', name: '1 percent cow milk', quantity: '2 L', category: 'dairy' },
    { id: 'w1-g21', name: 'Eggs large', quantity: '1 dozen', category: 'dairy' },
    { id: 'w1-g22', name: 'Greek yogurt plain 0 percent', quantity: 'large tub', category: 'dairy' },
    { id: 'w1-g23', name: 'All Bran cereal', quantity: '1 box', category: 'grains' },
    { id: 'w1-g24', name: 'Protein powder unsweetened', quantity: '1 tub', category: 'other' },
    { id: 'w1-g25', name: 'Chickpeas canned low-sodium', quantity: '2 cans', category: 'legumes' },
    { id: 'w1-g26', name: 'Black beans canned', quantity: '1 can', category: 'legumes' },
    { id: 'w1-g27', name: 'Bananas', quantity: '2 to 3', category: 'other' },
  ],
}

export const WEEK_2: WeekPlan = {
  week: 2,
  days: [week2Day6, week2Day7, week2Day8, week2Day9, week2Day10],
  snacks: [
    { id: 'w2-s1', name: 'Air Fryer Edamame', calories: 190, note: '1 cup frozen shelled edamame, olive oil spray, 380F 10 min.', alternative: 'Steamed edamame pods plus lemon (~160 kcal)' },
    { id: 'w2-s2', name: 'Beef Jerky low-sodium', calories: 80, note: '1 oz under 300mg sodium 0g added sugar. Check label.', alternative: 'Chicken jerky (~70 kcal)' },
    { id: 'w2-s3', name: 'Hummus and Veggie Sticks', calories: 100, note: '3 tbsp low-sodium hummus plus cucumber plus pepper plus celery.', alternative: 'White bean dip plus veggies (~90 kcal)' },
    { id: 'w2-s4', name: 'Banana Nice Cream', calories: 185, note: '1/2 frozen banana blended with 2 tbsp Greek yogurt plus splash milk. Eat immediately plus 5 almonds.', alternative: '1/2 banana plus 1 tbsp almond butter (~145 kcal)' },
    { id: 'w2-s5', name: 'Egg Salad Lettuce Cup', calories: 165, note: '2 eggs mashed with Greek yogurt plus celery plus Dijon plus pepper. Scoop into romaine leaf.', alternative: 'Devilled eggs cottage cheese filling (~130 kcal)' },
    { id: 'w2-s6', name: 'Cottage Cheese and Flax', calories: 145, note: '1/2 cup low-fat cottage cheese plus 1 tbsp ground flax plus pepper. Great before bed.', alternative: 'Ricotta plus walnuts plus cinnamon (~175 kcal)' },
  ],
  groceryList: [
    { id: 'w2-g1', name: 'Chicken thighs bone-in', quantity: '4 pcs', category: 'meat' },
    { id: 'w2-g2', name: 'Chicken breast', quantity: '1 pc', category: 'meat' },
    { id: 'w2-g3', name: 'Flank steak', quantity: '2 x 150g', category: 'meat' },
    { id: 'w2-g4', name: 'Beef strips sirloin or flank', quantity: '300g', category: 'meat' },
    { id: 'w2-g5', name: 'Lean ground beef 90 percent', quantity: '400g', category: 'meat' },
    { id: 'w2-g6', name: 'Pork chops boneless', quantity: '4', category: 'meat' },
    { id: 'w2-g7', name: 'Low-sodium beef jerky', quantity: '2 oz pkg', category: 'meat' },
    { id: 'w2-g8', name: 'Spinach baby', quantity: '1 large bag', category: 'vegetables' },
    { id: 'w2-g9', name: 'Asparagus', quantity: '1 bunch', category: 'vegetables' },
    { id: 'w2-g10', name: 'Mixed greens', quantity: '2 bags', category: 'vegetables' },
    { id: 'w2-g11', name: 'Bell peppers for stuffing and eating', quantity: '4', category: 'vegetables' },
    { id: 'w2-g12', name: 'Cherry tomatoes', quantity: '1 pint', category: 'vegetables' },
    { id: 'w2-g13', name: 'Cucumber', quantity: '2', category: 'vegetables' },
    { id: 'w2-g14', name: 'Cauliflower', quantity: '2 heads', category: 'vegetables' },
    { id: 'w2-g15', name: 'Mushrooms', quantity: '250g pkg', category: 'vegetables' },
    { id: 'w2-g16', name: 'Corn', quantity: '1 ear or frozen bag', category: 'vegetables' },
    { id: 'w2-g17', name: 'Small Yukon Gold potatoes', quantity: '3', category: 'vegetables' },
    { id: 'w2-g18', name: 'Frozen edamame shelled', quantity: '1 bag', category: 'vegetables' },
    { id: 'w2-g19', name: 'Avocados', quantity: '2 to 3', category: 'fats' },
    { id: 'w2-g20', name: 'Sesame oil', quantity: 'small bottle', category: 'fats' },
    { id: 'w2-g21', name: '1 percent cow milk', quantity: '2 L', category: 'dairy' },
    { id: 'w2-g22', name: 'Eggs large', quantity: '1 dozen', category: 'dairy' },
    { id: 'w2-g23', name: 'Greek yogurt plain 0 percent', quantity: 'replenish', category: 'dairy' },
    { id: 'w2-g24', name: 'Low-fat cottage cheese', quantity: 'replenish', category: 'dairy' },
    { id: 'w2-g25', name: 'Shredded low-sodium cheese', quantity: 'small pkg', category: 'dairy' },
    { id: 'w2-g26', name: 'All Bran cereal', quantity: 'replenish if low', category: 'grains' },
    { id: 'w2-g27', name: 'Steel-cut oats', quantity: 'small bag', category: 'grains' },
    { id: 'w2-g28', name: 'Chickpeas canned low-sodium', quantity: '1 can', category: 'legumes' },
    { id: 'w2-g29', name: 'Black beans canned', quantity: '1 can', category: 'legumes' },
    { id: 'w2-g30', name: 'Bananas', quantity: '2', category: 'other' },
    { id: 'w2-g31', name: 'Blueberries or raspberries', quantity: '1 cup', category: 'other' },
    { id: 'w2-g32', name: 'Frozen strawberries', quantity: '1 bag', category: 'other' },
  ],
}

export const WEEK_3: WeekPlan = {
  week: 3,
  days: [week3Day11, week3Day12, week3Day13, week3Day14, week3Day15],
  snacks: [
    { id: 'w3-s1', name: 'Corn and Cottage Cheese', calories: 170, note: '1/4 cup corn kernels plus 1/2 cup cottage cheese plus lime plus chili. Protein carries the carbs.', alternative: 'Roasted cherry tomatoes in cottage cheese (~120 kcal)' },
    { id: 'w3-s2', name: 'Mini Baked Potato Bites', calories: 155, note: '1/2 small potato baked plus cooled plus topped with Greek yogurt plus chives.', alternative: 'Air fryer cauliflower with paprika (~60 kcal)' },
    { id: 'w3-s3', name: 'Air Fryer Zucchini Chips', calories: 55, note: 'Sliced zucchini plus olive oil spray plus garlic powder. 370F 12 min. Crispy low-carb.', alternative: 'Air fryer cauliflower chips (~55 kcal)' },
    { id: 'w3-s4', name: 'Banana Oat Bites', calories: 195, note: '1/2 banana plus 3 tbsp oats plus cinnamon then microwave 90 sec. Pair with 1 tbsp almond butter.', alternative: '1/2 banana plus 1 hard-boiled egg (~120 kcal)' },
    { id: 'w3-s5', name: 'Avocado and Pepper Boats', calories: 160, note: '1/2 avocado mashed with lime plus chili flakes. Scoop into bell pepper strips. Zero cooking.', alternative: 'Avocado plus 2 sliced hard-boiled eggs (~230 kcal)' },
    { id: 'w3-s6', name: 'All Bran Milk Snack Cup', calories: 165, note: '1/2 cup All Bran plus 3/4 cup 1% milk. High fibre. Eat slowly very filling.', alternative: 'All Bran plus Greek yogurt instead of milk (~175 kcal)' },
  ],
  groceryList: [
    { id: 'w3-g1', name: 'Chicken thighs bone-in', quantity: '4 pcs', category: 'meat' },
    { id: 'w3-g2', name: 'Chicken breast', quantity: '2 pcs', category: 'meat' },
    { id: 'w3-g3', name: 'Chicken drumsticks', quantity: '4 to 6 pcs', category: 'meat' },
    { id: 'w3-g4', name: 'Lean ground beef 90 percent', quantity: '400g', category: 'meat' },
    { id: 'w3-g5', name: 'Firm tofu optional', quantity: '1 block', category: 'meat' },
    { id: 'w3-g6', name: 'Spinach baby plus frozen spinach', quantity: '1 bag plus 1 frozen', category: 'vegetables' },
    { id: 'w3-g7', name: 'Asparagus', quantity: '1 bunch', category: 'vegetables' },
    { id: 'w3-g8', name: 'Mixed greens', quantity: '2 bags', category: 'vegetables' },
    { id: 'w3-g9', name: 'Arugula', quantity: '1 bag', category: 'vegetables' },
    { id: 'w3-g10', name: 'Bell peppers', quantity: '4', category: 'vegetables' },
    { id: 'w3-g11', name: 'Cherry tomatoes', quantity: '1 pint', category: 'vegetables' },
    { id: 'w3-g12', name: 'Cucumber', quantity: '2', category: 'vegetables' },
    { id: 'w3-g13', name: 'Cauliflower', quantity: '1 head', category: 'vegetables' },
    { id: 'w3-g14', name: 'Zucchini', quantity: '2', category: 'vegetables' },
    { id: 'w3-g15', name: 'Corn', quantity: '1 ear or frozen bag', category: 'vegetables' },
    { id: 'w3-g16', name: 'Small Yukon Gold potatoes', quantity: '4', category: 'vegetables' },
    { id: 'w3-g17', name: 'Carrot sticks', quantity: '1 bag', category: 'vegetables' },
    { id: 'w3-g18', name: 'Frozen edamame shelled', quantity: '1 bag', category: 'vegetables' },
    { id: 'w3-g19', name: 'Avocados', quantity: '3 to 4', category: 'fats' },
    { id: 'w3-g20', name: 'Almond butter', quantity: 'check stock', category: 'fats' },
    { id: 'w3-g21', name: 'Pumpkin seeds', quantity: 'check stock', category: 'fats' },
    { id: 'w3-g22', name: 'Sliced almonds', quantity: 'small bag', category: 'fats' },
    { id: 'w3-g23', name: 'Flaxseed ground', quantity: 'check stock', category: 'fats' },
    { id: 'w3-g24', name: '1 percent cow milk', quantity: '2 L', category: 'dairy' },
    { id: 'w3-g25', name: 'Eggs large', quantity: '1 dozen', category: 'dairy' },
    { id: 'w3-g26', name: 'Greek yogurt plain 0 percent', quantity: 'replenish', category: 'dairy' },
    { id: 'w3-g27', name: 'Low-fat cottage cheese', quantity: 'replenish', category: 'dairy' },
    { id: 'w3-g28', name: 'Shredded low-sodium cheese', quantity: 'small pkg', category: 'dairy' },
    { id: 'w3-g29', name: 'Nutritional yeast', quantity: 'small bag', category: 'dairy' },
    { id: 'w3-g30', name: 'All Bran cereal', quantity: 'replenish if low', category: 'grains' },
    { id: 'w3-g31', name: 'Steel-cut oats', quantity: 'check stock', category: 'grains' },
    { id: 'w3-g32', name: 'Red lentils dry', quantity: '1 cup', category: 'legumes' },
    { id: 'w3-g33', name: 'Canned lentils speed option', quantity: '1 can', category: 'legumes' },
    { id: 'w3-g34', name: 'Chickpeas canned low-sodium', quantity: '2 cans', category: 'legumes' },
    { id: 'w3-g35', name: 'Bananas', quantity: '3', category: 'other' },
    { id: 'w3-g36', name: 'Blueberries or raspberries', quantity: '1 cup', category: 'other' },
    { id: 'w3-g37', name: 'Unsweetened cocoa powder', quantity: 'small tin', category: 'other' },
  ],
}

export const ALL_WEEKS: WeekPlan[] = [WEEK_1, WEEK_2, WEEK_3]

export function getWeek(weekNum: number): WeekPlan | undefined {
  return ALL_WEEKS.find(w => w.week === weekNum)
}

export function getDay(weekNum: number, dayNum: number): DayPlan | undefined {
  return getWeek(weekNum)?.days.find(d => d.day === dayNum)
}